// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4b0lnwwuSRPQO5HvwTZMQTUTh_s_91bY',
    appId: '1:953486504584:web:a646fb840b393c6849253d',
    messagingSenderId: '953486504584',
    projectId: 'riveanimation-88dd8',
    authDomain: 'riveanimation-88dd8.firebaseapp.com',
    storageBucket: 'riveanimation-88dd8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3uq5Oap4iylK6EySbOv9heo6evglmZT4',
    appId: '1:953486504584:android:43dc40a0bc40e7cc49253d',
    messagingSenderId: '953486504584',
    projectId: 'riveanimation-88dd8',
    storageBucket: 'riveanimation-88dd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChs7XfGPpG3Xc2nTvis0uxbia1uGhtWow',
    appId: '1:953486504584:ios:b9e45be25f903f5949253d',
    messagingSenderId: '953486504584',
    projectId: 'riveanimation-88dd8',
    storageBucket: 'riveanimation-88dd8.appspot.com',
    iosClientId: '953486504584-tedliookgekj02e44qc72ugndd0vvm75.apps.googleusercontent.com',
    iosBundleId: 'com.example.riveAnimation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChs7XfGPpG3Xc2nTvis0uxbia1uGhtWow',
    appId: '1:953486504584:ios:b9e45be25f903f5949253d',
    messagingSenderId: '953486504584',
    projectId: 'riveanimation-88dd8',
    storageBucket: 'riveanimation-88dd8.appspot.com',
    iosClientId: '953486504584-tedliookgekj02e44qc72ugndd0vvm75.apps.googleusercontent.com',
    iosBundleId: 'com.example.riveAnimation',
  );
}
